"""Remove LLaMA branding and em dashes from all files."""

# ── app.js ────────────────────────────────────────────────────────────────────
js = open('static/app.js', encoding='utf-8').read()

js = (js
  .replace('<span class="aip-header-badge">LLaMA 3.3 · 70B</span>', '<span class="aip-header-badge">AI Analysis</span>')
  .replace('<div class="aip-verdict-footer">Generated by LLaMA 3.3 70B via Groq</div>', '<div class="aip-verdict-footer">Powered by WebinarIQ AI</div>')
  .replace('Generating topics with LLaMA 3.3 70B', 'Generating topics with AI')
  .replace('Generated on ${esc(dateStr)} · Powered by LLaMA 3.3 70B via Groq', 'Generated on ${esc(dateStr)} · Powered by WebinarIQ AI')
  .replace('<div class="chatbot-hd-sub">Powered by LLaMA 3.3 · 70B</div>', '<div class="chatbot-hd-sub">WebinarIQ AI Assistant</div>')
  # em dash in chatbot welcome message
  .replace('Hi! I can answer any question about your webinars — attendance rates, top s',
           'Hi! I can answer any question about your webinars. Ask me about attendance rates, top s')
)

# Full welcome message fix
js = js.replace(
    'Hi! I can answer any question about your webinars. Ask me about attendance rates, top speakers, ICP breakdown, trends, and more. What would you like to know?',
    'Hi! I can answer any question about your webinars. Ask me about attendance rates, top speakers, ICP breakdown, trends and more. What would you like to know?'
)

open('static/app.js', 'w', encoding='utf-8').write(js)
print('app.js: LLaMA removed, em dashes fixed')

# ── main.py ───────────────────────────────────────────────────────────────────
py = open('main.py', encoding='utf-8').read()
py = (py
  .replace('You are WebinarIQ Assistant — an AI analyst', 'You are WebinarIQ Assistant, an AI analyst')
  .replace('GIFT City rapidly expanding — new fund categories approved', 'GIFT City rapidly expanding, new fund categories approved')
  .replace('SIF (Specialised Investment Funds) — new SEBI category launched', 'SIF (Specialised Investment Funds), new SEBI category launched')
  .replace('Budget FY27 — higher capital gains tax', 'Budget FY27: higher capital gains tax')
  .replace('Gold at record highs — ', 'Gold at record highs, ')
  .replace('"hook": "one sharp sentence — why this topic right now, what\'s the tension"',
           '"hook": "one sharp sentence on why this topic is urgent right now and the tension it creates"')
  .replace('say them — use ₹ figures', 'say them, use ₹ figures')
  .replace('Be specific — use the actual numbers. Be direct, not generic.', 'Be specific, use the actual numbers. Be direct, not generic.')
  .replace('Registration timeline — days before webinar', 'Registration timeline: days before webinar')
)
open('main.py', 'w', encoding='utf-8').write(py)
print('main.py: em dashes fixed')

# ── Verify ────────────────────────────────────────────────────────────────────
for fname in ['static/app.js', 'main.py']:
    content = open(fname, encoding='utf-8').read()
    llama = content.count('LLaMA')
    dash  = content.count('—')
    print(f'{fname}: LLaMA={llama}, em-dash={dash}')
